name: 02 - Evento issue
on: 
    push:
    issues:
        types:
            -   opened
    path-ignore:
        - '*.md' 

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "¡Hola Mundo!"